XRAYJENKINS-52 features files are now being upload in a single Zip file
xpandit/xrayjenkins pull request #7
Opened 2019-10-02 15:35 UTC by Russell616

2019-10-03 09:02 UTC, dmoduarte commented
- [ ] Validate this improvement with remote agents

2019-10-03 09:10 UTC, dmoduarte requested changes

2019-10-03 09:10 UTC, dmoduarte commented on src/main/java/com/xpandit/plugins/xrayjenkins/task/filefilters/OnlyFeatureFilesInPathFilter.java
> +
Please add javadoc explaining the goal of this class, the criteria of the filter, etc

2019-10-03 10:43 UTC, tomasvcaldas commented on src/main/java/com/xpandit/plugins/xrayjenkins/Utils/FileUtils.java
> +                                                               TaskListener listener) throws IOException, InterruptedException {
Isn't javadoc needed here?

2019-10-03 10:52 UTC, Russell616 commented on src/main/java/com/xpandit/plugins/xrayjenkins/Utils/FileUtils.java
> +                                                               TaskListener listener) throws IOException, InterruptedException {
You are absolutely right :)

2019-10-03 12:34 UTC, tomasvcaldas approved these changes

2019-10-04 09:11 UTC, dmoduarte approved these changes

2019-10-04 09:11 UTC, merged